### ISSUE TITLE
Issues with Hello World example

### ISSUE THREAD

**Issue by pkmitre** [standardhealth/shr-cli#143]
When running the [Hello World](https://github.com/standardhealth/shr-cli/wiki/Hello-World) example there are a few issues:

1) When running the command `node . ../hello_world/` the following error is reported:

```[21:56:38.790Z] FATAL shr: Failure in FHIR export. Aborting with error message: Error: ENOENT: no such file or directory, lstat '../hello_world/exampleIndexContent.html'```

Creating the exampleIndexContent.html file resolves this issue.

2) When running the IG Generation step the following errors are reported:

```
java.lang.NullPointerException
at org.hl7.fhir.igtools.publisher.ConfigFileConverter.convert(ConfigFileConverter.java:108)
at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:1068)
at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:507)
at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:4895)
```
and
```
java.lang.Exception: A package name (npm-name) is required to publish implementation guides. For further information, see http://wiki.hl7.org/index.php?title=FHIR_NPM_Package_Spec#Package_name
at org.hl7.fhir.igtools.publisher.Publisher.load(Publisher.java:1691)
at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:566)
at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:510)
at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:4895)
Exception in thread "main" java.lang.NullPointerException
at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:4905)
```

The second error seems be referred to in issue #126. There is a config.json file generated by the node command in the hello_world directory; adding npmName and version to the "implementationGuide" section of the config.json file appears to address both issues.

Environment:

macOS 10.13.6

```
> java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

> node --version
v11.7.0
```

**Comment by markkramerus** [comment]
Hello World has been tested by Mint, Carmela, and Nick. Retiring this bug.
