### ISSUE TITLE
Crash when element name doesn't have leading Capitalization

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#23]
CLI crashes if you try to define an element whose name begins with lower case letter. This error should be handled and an appropriate error message produced. Here's the backtrace:

shr-cli-5.0.0-beta.6\node_modules\shr-text-import\lib\dataElementListener.js:278
    } else if (ctx.primitive()) {
                   ^

TypeError: ctx.primitive is not a function
    at DataElementImporter.processType (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6\node_modules\shr-text-import\lib\dataElementListener.js:278:20)
    at DataElementImporter.processCountAndTypes (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6\node_modules\shr-text-import\lib\dataElementListener.js:203:17)
    at DataElementImporter.enterField (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6\node_modules\shr-text-import\lib\dataElementListener.js:150:24)
    at FieldContext.enterRule (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6\node_modules\shr-text-import\lib\parsers\SHRDataElementParser.js:2084:18)
    at ParseTreeWalker.enterRule (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6\node_modules\antlr4\tree\Tree.js:207:6)
    at ParseTreeWalker.walk (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6\node_modules\antlr4\tree\Tree.js:190:8)
    at ParseTreeWalker.walk (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6\node_modules\antlr4\tree\Tree.js:193:9)
    at ParseTreeWalker.walk (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6\node_modules\antlr4\tree\Tree.js:193:9)
    at ParseTreeWalker.walk (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6\node_modules\antlr4\tree\Tree.js:193:9)
    at ParseTreeWalker.walk (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6\node_modules\antlr4\tree\Tree.js:193:9)

C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.6>node . C:\Users\mkramer\Documents\GitHub\cimi -l error

**Comment by Abhijay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crash when element name doesn't have leading Capitalization](https://trello.com/c/Hs3KTvg6/6-crash-when-element-name-doesnt-have-leading-capitalization)

**Comment by Abhijay** [comment]
Just to ensure I'm understanding this correctly: From the ANTLR grammar, it seems the element name was intentionally meant to start with an Uppercase Letter. Is what you're looking for is for an error to be raised when the element name is lowercase (as opposed to crashing)?

**Comment by Abhijay** [comment]
(For proper bookkeeping)

Resolved by commits: 
https://github.com/standardhealth/shr-text-import/commit/0fb1021657d20cd6126cea3079de8a536bca16ca
https://github.com/standardhealth/shr-grammar/commit/103b09dcf8c2d7feae6754aefefb93311a440bb9

Once reviewed by @cmoesel and merged into main grammar_5 branch, issue can be closed.
