### ISSUE TITLE
CLI crash if Value element is not defined

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#26]
CLI crashes when a Value element is undefined. The example below:

I misspelled the element "Attribution" that acts a Value for another element. CLI finds that error (the initial "Failed to resolve" error message is correct, but then CLI crashes when the element.value is undefined.
---------------------------------
[13:29:43.193Z] ERROR shr: Failed to resolve definition for **Attributions**. (module=shr-text-input, shrId=cimi.clinicaladversereaction.Asserter)
    file: C:\Users\mkramer\Documents\GitHub\cimi\cimi_adversereaction.txt
C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\common.js:94
  if (typeof element.value !== 'undefined') {
                    ^

TypeError: Cannot read property 'value' of undefined
    at Object.valueAndFields (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\common.js:94:21)
    at FHIRExporter.buildUnmappedPathsTree (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\export.js:237:32)
    at FHIRExporter.addFieldToUnmappedPathsTree (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\export.js:253:45)
    at FHIRExporter.buildUnmappedPathsTree (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\export.js:238:12)
    at FHIRExporter.addFieldToUnmappedPathsTree (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\export.js:253:45)
    at FHIRExporter.buildUnmappedPathsTree (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\export.js:238:12)
    at FHIRExporter.addFieldToUnmappedPathsTree (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\export.js:253:45)
    at FHIRExporter.buildUnmappedPathsTree (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\export.js:238:12)
    at FHIRExporter.mappingToProfile (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\export.js:158:56)
    at FHIRExporter.export (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.7\node_modules\shr-fhir-export\lib\export.js:64:12)

**Comment by Abhijay** [comment]
(For proper bookkeeping)

Resolved by commits:
https://github.com/standardhealth/shr-fhir-export/commit/00343a39bbd53adbb3ec9f025f4e64f8a6f68816
https://github.com/standardhealth/shr-fhir-export/commit/f7e3bc525978543584ea3c08b87f61b23bf1fe29

Once reviewed by @cmoesel and merged into main grammar_5 branch, issue can be closed.

**Comment by cmoesel** [comment]
Fixed in SHR CLI 5.0.0 Beta 8.
