### ISSUE TITLE
Need --skip argument for javadoc

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#92]
I'm hitting a crash that seems to originate in the javadoc exporter (see traceback below). I realized I could get around it if I could skip that export. But the only "skips" are json, fhir, and all. I could use "all" but then I can't test the FHIR maps. So there are two things: (1) add the skip argument for every exporter, (2) fix the crash.  Here's the traceback: 
```
C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:153
    var constraintName = (this.field.valueType === 'RefValue') ? `ref(${element.name})` : element.name;
                                                                                                 ^

TypeError: Cannot read property 'name' of undefined
    at Constraints.typeConstraint (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:153:98)
    at Constraints.switchConstraintType (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:214:12)
    at Object.keys.forEach (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:234:14)
    at Array.forEach (native)
    at Constraints.parse (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:232:43)
    at new Constraints (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:35:10)
    at element.fields.forEach (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\elements.js:144:18)
    at Array.forEach (native)
    at Elements.updateFields (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\elements.js:128:20)
    at list.forEach (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\elements.js:160:12)
```

**Comment by markkramerus** [comment]
Test on the shimi branch, commit labeled "Exporter issue #92" (on 5/2/2018 at 7:18 pm) and 5.7.2 (also shows the same error on 5.7.1)

**Comment by Abhijay** [comment]
You should be able to skip it with '-s model-doc'

**Comment by Abhijay** [comment]
I'll look into the crash and see what's going on there.

**Comment by Abhijay** [comment]
@markkramerus I don't see a commit labeled "Exporter issue #92" on the shimmy branch (or any other branch). Can you double check to make sure it was pushed?
